Vagrant::Config.run do |config|

  config.vm.box = "ubuntu-lucid-32"
  config.vm.forward_port "web", 80, 8000
  config.vm.share_folder("nodebox-app", "/nodebox-app", "./../")

  config.vm.provision :chef_solo do | chef |
    chef.cookbooks_path = ["cookbooks"]
    chef.add_recipe("nodebox-app")
    chef.json.merge!({
      :appname => "nodebox-app",
      :node_user => "vagrant",
      :nodejs => {
        :version => "0.2.6"
      },
      :node_modules => [ "express", "nodeunit", "mongoose" ]
    });
  end

end

