# TODO explain the difference
NODEBOX_PRODUCTION = {
  :port => 8080,
  :recipe => 'nodebox-app-production'
}

NODEBOX_DEVELOPMENT = {
  :port => 80,
  :recipe => 'nodebox-app-development'
}

# TODO explain the difference between the two box setups
nodebox_env = NODEBOX_PRODUCTION # or NODEBOX_DEVELOPMENT

app_name = 'nodebox-app'
app_path = "/var/www/#{app_name}"

Vagrant::Config.run do |config|

  config.vm.box = "ubuntu-lucid-32"
  config.vm.forward_port "web", 80, 8000
  config.vm.share_folder(app_name, app_path, "./../")

  config.vm.provision :chef_solo do | chef |
    chef.cookbooks_path = [ "cookbooks", "site-cookbooks" ]
    chef.add_recipe(nodebox_env[:recipe])
    chef.json.merge!({
      :app => {
        :name => app_name,
        :port => nodebox_env[:port],
        :path => app_path,
      },
      :node_user => "node",
      :nodejs => {
        :version => "0.4.0"
      },
      :node_modules => [ "express", "nodeunit", "mongoose" ]
    });
  end

end

